// Asset Provider Registration

// User Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const ADD_JOGGERS_TO_CART = "ADD_JOGGERS_TO_CART";
export const ADD_ASOOKE_TO_CART = "ADD_ASOOKE_TO_CART";
export const GET_ITEM_IN_CART_REQUEST = "GET_ITEM_IN_CART_REQUEST";
export const GET_ITEM_IN_CART_SUCCESS = "GET_ITEM_IN_CART_SUCCESS";
export const GET_ITEM_IN_CART_ERROR = "GET_ITEM_IN_CART_ERROR";

export const GET_SHOWCASE_REQUEST = "GET_SHOWCASE_REQUEST";
export const GET_SHOWCASE_SUCCESS = "GET_SHOWCASE_SUCCESS";
export const GET_SHOWCASE_ERROR = "GET_SHOWCASE_ERROR";

// joggers

export const GETALL_JOGGERS_REQUEST = "GETALL_JOGGERS_REQUEST";
export const GETALL_JOGGERS_SUCCESS = "GETALL_JOGGERS_SUCCESS";
export const GETALL_JOGGERS_ERROR = "GETALL_JOGGERS_ERROR";

export const GET_JOGGER_REQUEST = "GET_JOGGER_REQUEST";
export const GET_JOGGER_SUCCESS = "GET_JOGGER_SUCCESS";
export const GET_JOGGER_ERROR = "GET_JOGGER_ERROR";

export const SEARCH_FOR_JOGGERS = "SEARCH_FOR_JOGGERS";
